### ISSUE TITLE
Simulator closes when I try to name myself "Gaster"

### ISSUE THREAD

**Issue by yoyomonem** [kckarnige/BadTimeRevamped#5]
When I name myself __"Gaster"__, the Bad Time Simulator closes!

**Comment by VegitoSsjb** [comment]
Me who knows:  (:<

You who doesn't know:  >:(

**Comment by yoyomonem** [comment]
> @VegitoSsjb said:
> Me who knows: (:<
> 
> You who doesn't know: >:(

i knew once i found out it closes >:)
